server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: lore-master-admin

  # 数据源配置
  datasource:
    consumer:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lore_consumer?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        pool-name: ConsumerHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    # 管理端数据源（管理端数据库 - lore_admin）
    admin:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lore_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        auto-commit: true
        idle-timeout: 30000
        pool-name: AdminHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    # B端数据源（B端业务数据库 - lore_business）
    business:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lore_business?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        auto-commit: true
        idle-timeout: 30000
        pool-name: BusinessHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    # 存储数据源（文件存储数据库 - lore_middleware）
    storage:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lore_middleware?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        auto-commit: true
        idle-timeout: 30000
        pool-name: StorageHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# JPA配置
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# LangChain4j配置 - 暂时注释，等基本功能稳定后再启用
# langchain4j:
#   open-ai:
#     chat-model:
#       api-key: ${OPENAI_API_KEY:your-api-key-here}
#       model-name: gpt-3.5-turbo
#       temperature: 0.7
#       max-tokens: 1000

# 日志配置
logging:
  level:
    com.lore.master: INFO
    org.springframework.web: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# 管理端配置
lore:
  admin:
    # 跨域配置
    cors:
      allowed-origins:
        - http://localhost:3001
        - http://127.0.0.1:3001
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true

llm:
  # API密钥（建议通过环境变量设置）
  api:
    key: ${LLM_API_KEY:default-value}
  # 模型配置
  ollama:
    url: http://localhost:11434
    model: ${LLM_MODEL:qwen3:0.6b}