# 通学万卷 - C端用户应用配置
server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: lore-master-consumer
  
  # 数据源配置
  datasource:
    # 主数据源（C端用户数据库）
    consumer:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lore_consumer?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        pool-name: ConsumerHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    # 存储数据源（文件存储数据库 - lore_middleware）
    storage:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lore_middleware?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        auto-commit: true
        idle-timeout: 30000
        pool-name: StorageHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 2
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# 日志配置
logging:
  level:
    com.lore.master: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/lore-master-consumer.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 自定义配置
lore:
  consumer:
    # JWT配置
    jwt:
      secret: lore-master-consumer-jwt-secret-key-2025
      expiration: 86400 # 24小时
      refresh-expiration: 604800 # 7天
    
    # 验证码配置
    verify-code:
      expire-time: 300 # 5分钟
      length: 6
      
    # 用户配置
    user:
      default-avatar: https://example.com/default-avatar.png
      max-nickname-length: 50
      
    # 学习配置
    study:
      daily-goal: 30 # 每日学习目标（分钟）
      level-up-score: 100 # 升级所需积分

# 文件存储配置
file-storage:
  # 存储策略：mysql（存储到数据库）
  strategy: mysql

  # 最大文件大小（字节）- 10MB
  max-file-size: 10485760

  # 允许的文件类型
  allowed-types:
    - image/jpeg
    - image/jpg
    - image/png
    - image/gif
    - image/webp

  # 临时文件过期时间（小时）
  temp-file-expire-hours: 24

  # 是否启用文件去重
  enable-deduplication: true

  # 是否启用访问日志
  enable-access-log: true

  # 默认存储桶名称
  default-bucket-name: avatars

  # URL签名过期时间（分钟）
  url-expire-minutes: 60

  # MySQL存储配置
  mysql:
    # 是否压缩存储
    enable-compression: false
    # 压缩阈值（字节）
    compression-threshold: 1048576  # 1MB
